[project]
name = "jbig2-pdf-optimiser"
version = "0.1.2"
description = "Recompress 1-bit images in PDFs with global dictionary JBIG2 images"
requires-python = ">=3.12"
dependencies = [
    "pikepdf",
    "pandas",
    "tqdm",
    "numpy",
]
